package com.wakakusa.kutportal;

import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.view.View;
import android.support.design.widget.NavigationView;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Button;
import android.widget.TextView;
import android.view.View.OnClickListener;
import android.content.ContentValues;

public class NewsPage extends BasePage {
    int i=1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_news_page);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        setNews();

        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.setDrawerListener(toggle);
        toggle.syncState();

        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);

        final DatabaseWriter dbWriter = new DatabaseWriter(this, "news");
        //データベースへの書き込み(初期値false)
        /*ContentValues cvalue = new ContentValues();
         cvalue.put("newscode","1");
         cvalue.put("day","2017/1/1");
         cvalue.put("title","どうも1");
         cvalue.put("adduser","一郎");
         cvalue.put("content","どうも一郎やで");
         dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","2");
        cvalue.put("day","2017/1/2");
        cvalue.put("title","どうも2");
        cvalue.put("adduser","二郎");
        cvalue.put("content","どうも二郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","3");
        cvalue.put("day","2017/1/3");
        cvalue.put("title","どうも3");
        cvalue.put("adduser","三郎");
        cvalue.put("content","どうも三郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","4");
        cvalue.put("day","2017/1/4");
        cvalue.put("title","どうも4");
        cvalue.put("adduser","四郎");
        cvalue.put("content","どうも四郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","5");
        cvalue.put("day","2017/1/5");
        cvalue.put("title","どうも5");
        cvalue.put("adduser","五郎");
        cvalue.put("content","どうも五郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","6");
        cvalue.put("day","2017/1/6");
        cvalue.put("title","どうも6");
        cvalue.put("adduser","六郎");
        cvalue.put("content","どうも六郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","7");
        cvalue.put("day","2017/1/7");
        cvalue.put("title","どうも7");
        cvalue.put("adduser","七郎");
        cvalue.put("content","どうも七郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","8");
        cvalue.put("day","2017/1/8");
        cvalue.put("title","どうも8");
        cvalue.put("adduser","八郎");
        cvalue.put("content","どうも八郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","9");
        cvalue.put("day","2017/1/9");
        cvalue.put("title","どうも9");
        cvalue.put("adduser","九郎");
        cvalue.put("content","どうも九郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","10");
        cvalue.put("day","2017/1/10");
        cvalue.put("title","どうも10");
        cvalue.put("adduser","十郎");
        cvalue.put("content","どうも十郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","11");
        cvalue.put("day","2017/1/11");
        cvalue.put("title","どうも11");
        cvalue.put("adduser","十一郎");
        cvalue.put("content","どうも十一郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","12");
        cvalue.put("day","2017/1/12");
        cvalue.put("title","どうも12");
        cvalue.put("adduser","十二郎");
        cvalue.put("content","どうも十二郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","13");
        cvalue.put("day","2017/1/13");
        cvalue.put("title","どうも13");
        cvalue.put("adduser","十三郎");
        cvalue.put("content","どうも十三郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","14");
        cvalue.put("day","2017/1/14");
        cvalue.put("title","どうも14");
        cvalue.put("adduser","十四郎");
        cvalue.put("content","どうも十四郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","15");
        cvalue.put("day","2017/1/15");
        cvalue.put("title","どうも15");
        cvalue.put("adduser","十五郎");
        cvalue.put("content","どうも十五郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","16");
        cvalue.put("day","2017/1/16");
        cvalue.put("title","どうも16");
        cvalue.put("adduser","十六郎");
        cvalue.put("content","どうも十六郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","17");
        cvalue.put("day","2017/1/17");
        cvalue.put("title","どうも17");
        cvalue.put("adduser","十七郎");
        cvalue.put("content","どうも十七郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","18");
        cvalue.put("day","2017/1/18");
        cvalue.put("title","どうも18");
        cvalue.put("adduser","十八郎");
        cvalue.put("content","どうも十八郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","19");
        cvalue.put("day","2017/1/19");
        cvalue.put("title","どうも19");
        cvalue.put("adduser","十九郎");
        cvalue.put("content","どうも十九郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","20");
        cvalue.put("day","2017/1/20");
        cvalue.put("title","どうも20");
        cvalue.put("adduser","二十郎");
        cvalue.put("content","どうも二十郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","21");
        cvalue.put("day","2017/1/21");
        cvalue.put("title","どうも21");
        cvalue.put("adduser","二十一郎");
        cvalue.put("content","どうも二十一郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","22");
        cvalue.put("day","2017/1/22");
        cvalue.put("title","どうも22");
        cvalue.put("adduser","二十二郎");
        cvalue.put("content","どうも二十二郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","23");
        cvalue.put("day","2017/1/23");
        cvalue.put("title","どうも23");
        cvalue.put("adduser","二十三郎");
        cvalue.put("content","どうも二十三郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","24");
        cvalue.put("day","2017/1/24");
        cvalue.put("title","どうも24");
        cvalue.put("adduser","二十四郎");
        cvalue.put("content","どうも二十四郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","25");
        cvalue.put("day","2017/1/25");
        cvalue.put("title","どうも25");
        cvalue.put("adduser","二十五郎");
        cvalue.put("content","どうも二十五郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","26");
        cvalue.put("day","2017/1/26");
        cvalue.put("title","どうも26");
        cvalue.put("adduser","二十六郎");
        cvalue.put("content","どうも二十六郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","27");
        cvalue.put("day","2017/1/27");
        cvalue.put("title","どうも27");
        cvalue.put("adduser","二十七郎");
        cvalue.put("content","どうも二十七郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","28");
        cvalue.put("day","2017/1/28");
        cvalue.put("title","どうも28");
        cvalue.put("adduser","二十八郎");
        cvalue.put("content","どうも二十八郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","29");
        cvalue.put("day","2017/1/29");
        cvalue.put("title","どうも29");
        cvalue.put("adduser","二十九郎");
        cvalue.put("content","どうも二十九郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);
        cvalue.put("newscode","30");
        cvalue.put("day","2017/1/30");
        cvalue.put("title","どうも30");
        cvalue.put("adduser","三十郎");
        cvalue.put("content","どうも三十郎やで");
        dbWriter.write.insert(dbWriter.Table_name,null, cvalue);*/
        //dbWriter.deleteDB2("adduser","二十一郎"); //データベース全削除
        final DatabaseReader rd = new DatabaseReader(this, "news");
        String[] str = {"newscode","day","title","adduser","content"};
        String s = rd.readDB(str,0);
        System.out.println(s);
        Button btn1 = (Button)findViewById(R.id.news1);
        Button btn2 = (Button)findViewById(R.id.news2);
        Button btn3 = (Button)findViewById(R.id.news3);
        btn1.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                i=1;
                System.out.println(i);
                setNews(); }
        });
        btn2.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                i=51;
                System.out.println(i);
                setNews();
            } });
        btn3.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                i=101;
                System.out.println(i);
                setNews(); }
        });
    }
    private  void setNews() {
        final DatabaseReader rd = new DatabaseReader(this, "news");
        String[] str = {"newscode","day","title","adduser","content"};
        TextView tex1 = (TextView) findViewById(R.id.newscontent1);
        TextView tex2 = (TextView) findViewById(R.id.newscontent2);
        TextView tex3 = (TextView) findViewById(R.id.newscontent3);
        TextView tex4 = (TextView) findViewById(R.id.newscontent4);
        TextView tex5 = (TextView) findViewById(R.id.newscontent5);
        TextView tex6 = (TextView) findViewById(R.id.newscontent6);
        TextView tex7 = (TextView) findViewById(R.id.newscontent7);
        TextView tex8 = (TextView) findViewById(R.id.newscontent8);
        TextView tex9 = (TextView) findViewById(R.id.newscontent9);
        TextView tex10 = (TextView) findViewById(R.id.newscontent10);
        TextView tex11 = (TextView) findViewById(R.id.newscontent11);
        TextView tex12 = (TextView) findViewById(R.id.newscontent12);
        TextView tex13 = (TextView) findViewById(R.id.newscontent13);
        TextView tex14 = (TextView) findViewById(R.id.newscontent14);
        TextView tex15 = (TextView) findViewById(R.id.newscontent15);
        TextView tex16 = (TextView) findViewById(R.id.newscontent16);
        TextView tex17 = (TextView) findViewById(R.id.newscontent17);
        TextView tex18 = (TextView) findViewById(R.id.newscontent18);
        TextView tex19 = (TextView) findViewById(R.id.newscontent19);
        TextView tex20 = (TextView) findViewById(R.id.newscontent20);
        TextView tex21 = (TextView) findViewById(R.id.newscontent21);
        TextView tex22 = (TextView) findViewById(R.id.newscontent22);
        TextView tex23 = (TextView) findViewById(R.id.newscontent23);
        TextView tex24 = (TextView) findViewById(R.id.newscontent24);
        TextView tex25 = (TextView) findViewById(R.id.newscontent25);
        TextView tex26 = (TextView) findViewById(R.id.newscontent26);
        TextView tex27 = (TextView) findViewById(R.id.newscontent27);
        TextView tex28 = (TextView) findViewById(R.id.newscontent28);
        TextView tex29 = (TextView) findViewById(R.id.newscontent29);
        TextView tex30 = (TextView) findViewById(R.id.newscontent30);
        String s = rd.readDB(str,0); //データベースから読み出し
        String[] s2 = s.split("\n", 0); //データの分割
        tex1.setText(s2[i]);
        tex2.setText(s2[i + 1]);
        tex3.setText("送信者 " + s2[i + 2]);
        tex4.setText(s2[i + 5]);
        tex5.setText(s2[i + 6]);
        tex6.setText("送信者 " + s2[i + 7]);
        tex7.setText(s2[i + 10]);
        tex8.setText(s2[i + 11]);
        tex9.setText("送信者 " + s2[i + 12]);
        tex10.setText(s2[i + 15]);
        tex11.setText(s2[i + 16]);
        tex12.setText("送信者 " + s2[i + 17]);
        tex13.setText(s2[i + 20]);
        tex14.setText(s2[i + 21]);
        tex15.setText("送信者 " + s2[i + 22]);
        tex16.setText(s2[i + 25]);
        tex17.setText(s2[i + 26]);
        tex18.setText("送信者 " + s2[i + 27]);
        tex19.setText(s2[i + 30]);
        tex20.setText(s2[i + 31]);
        tex21.setText("送信者 " + s2[i + 32]);
        tex22.setText(s2[i + 35]);
        tex23.setText(s2[i + 36]);
        tex24.setText("送信者 " + s2[i + 37]);
        tex25.setText(s2[i + 40]);
        tex26.setText(s2[i + 41]);
        tex27.setText("送信者 " + s2[i + 42]);
        tex28.setText(s2[i + 45]);
        tex29.setText(s2[i + 46]);
        tex30.setText("送信者 " + s2[i + 47]);
    }
}